
@extends('layouts.app')
@section('content')
<div class="row mt-5">
    <div class="page-title">
        <h1>Terms &amp; Conditions</h1>
    </div>
            <div class="std"><p class="p1"><span class="s1"><strong>By agreeing to the terms on this site (the “Website,”) You agree to the following Terms and Conditions set forth below with CorporateGift. PLEASE READ THESE TERMS CAREFULLY. If You do not agree, exit the site and not use it further.&nbsp;</strong></span></p>
        <p class="p2">&nbsp;<strong>THIS CUSTOMER AGREEMENT </strong>(the “Agreement”) is entered into by and between CorporateGift.com, Inc., a corporation organized under the laws of the state of Delaware, (“CorporateGift”) and You (“Customer” or “You”).</p>
        <p class="p2"><span class="s1">&nbsp;</span>WHEREAS, CorporateGift is a corporate gift giving marketplace in the business of offering companies a variety of gifts they can purchase for employees, clients, or others. &nbsp;</p>
        <p class="p1"><span class="s1">WHEREAS, the parties desire to enter into an agreement to provide these gifts;</span></p>
        <p class="p1"><span class="s1">THEREFORE, the parties agree as follows:</span></p>
        <p class="p2">&nbsp;1. <span style="text-decoration: underline;">Definitions</span>.</p>
        <p class="p3"><span class="s1">“<strong>Customer</strong>” shall mean the corporate customer who places the order with CorporateGift.</span></p>
        <p class="p3"><span class="s1">“<strong>Products</strong>” shall mean the products ordered by Customer to be delivered to the Recipient, as applicable.</span></p>
        <p class="p3"><span class="s1">“<strong>Recipient</strong>” shall, if an order is placed through the eGift site, mean the end person who receives the Product, either directly or through the re-gifting process.&nbsp;</span></p>
        <p class="p1"><span class="s2">2. <span style="text-decoration: underline;">Privacy</span>.</span><span class="s1">&nbsp; By entering this Website, You are agreeing to CorporateGift’s Privacy Policy, the terms of this may be found at http://corporategift.com/privacy-policy/</span><span class="s1">.</span></p>
        <p class="p1"><span class="s2">3.&nbsp;<span style="text-decoration: underline;">Orders</span>.&nbsp; </span><span class="s1">You must be at least 13 years old to access and use the Website. If you are between the ages of 13 and 18 years old, you may use and access the Website only under the supervision of your parent or guardian who has agreed to be bound by this Agreement. Customer places an order on the CorporateGift Website and either a) enters Customer address for direct ship to Customer, or b) enters the Recipient email address. The Recipient can accept the Product , choose to re-gift that Product to another recipient, or “buy-up” to another Product offered on the Website. All information that you provide must be accurate, truthful, current, and complete. You accept all risks of unauthorized access and use relating to your use of the Service and will notify us promptly if you discover or suspect any unauthorized access or use.</span></p>
        <p class="p1"><span class="s2">4.&nbsp;<span style="text-decoration: underline;">Payment</span></span><span class="s1">. Customer will make the payment at the time of placing the order, including taxes and shipping. Payments are processed by CorporateGift’s third party payment processor, and Customer is responsible for reviewing all applicable terms and policies.&nbsp; CorporateGift is not responsible for acts or omissions of the payment processing party.</span></p>
        <p class="p4"><span class="s2">5.&nbsp;Restrictions on Orders.</span><span class="s1"> &nbsp;</span></p>
        <p class="p4"><span class="s1">A .By placing an order on this Website, You represent and warrant that You are 18 years or older. In the event that You place an order for a Product containing alcohol, You represent and warrant that the Recipient, if applicable, that You designate is age 21 or older.</span></p>
        <p class="p4"><span class="s1">B. CorporateGift does not ship outside the contiguous United States.&nbsp;</span></p>
        <p class="p1"><span class="s1">C. CorporateGift does not guarantee availability of a Product at the time it is ordered.&nbsp;</span></p>
        <p class="p4"><span class="s1">D. CorporateGift does not offer refunds.&nbsp; Products which are damaged in transit will be replaced.&nbsp;</span></p>
        <p class="p1"><span class="s2">6. <span style="text-decoration: underline;">Restrictions</span>, Generally.</span><span class="s1"> Customer is responsible for its own conduct with respect to the gifting service or this Website.&nbsp; You may not modify, port, translate, or create a derivative work of the Website; decompile, reverse engineer, disassemble, attempt to derive the source code, underlying ideas, algorithms of the gifting service or Website; stalk, intimidate, harass, or cause discomfort to other users, of the Website, by sending gifts to harass Recipients, or sending unwanted or objectionable gifts. Violation of this section will automatically terminate Customer’s right to use this site.</span></p>
        <p class="p1"><span class="s2">7. <span style="text-decoration: underline;">Copyright &amp; Trademark Notice &amp; Rights</span></span><span class="s1">. &nbsp; CorporateGift permits Customer to use its logos, labels, slogans, and captions (“Trademarks”) of CorporateGifts.com in the furtherance of its corporate gift giving. Customer may not modify any Trademarks or any portions thereof.&nbsp; You are not granted any rights in or to the Website by implication, estoppel, or other legal theory, and all rights in and to the gifting service not expressly granted in this Agreement are hereby reserved and retained by CorporateGift.</span></p>
        <p class="p1"><span class="s2">8. <span style="text-decoration: underline;">No Warranties, Express or Implied</span></span><span class="s1">. CorporateGift assumes no liability for the use or disclosure of any information or content contained herein. All Product and brand names mentioned on this Website are trademarks of their respective owners. CorporateGift does not endorse or a recommend any particular Product on its Website.&nbsp; The information on this Website is provided "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF THIRD PARTY RIGHTS. Although CorporateGift has attempted to provide accurate and timely information on this Website, CorporateGift assumes no responsibility in connection therewith. CorporateGift reserves the right to alter or delete any Products offered herein without notice. IN NO EVENT SHALL CORPORATEGIFT BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND, including, without limitation, lost profits or damages resulting from the use of or reliance upon any information provided on this Website.</span></p>
        <p class="p4"><span class="s2">9. <span style="text-decoration: underline;">Indemnification</span></span><span class="s1">.&nbsp; Customer shall indemnify CorporateGift for any liability, including reasonable legal fees and reasonable costs for any violation of this Agreement by Customer.&nbsp; The Customer shall indemnify and save and hold CorporateGift, its, subsidiaries, employees, officers, directors, subcontractors, and agents harmless from any and all claims, demands, suits, costs, judgments or other forms of liability to third parties, actual or claimed (whether or not such allegations may be false, fraudulent or groundless), including attorney fees, for representations made by Customer under this Agreement. Upon timely written notice from CorporateGift, the Customer shall defend CorporateGift in any such action or proceeding brought thereon.&nbsp;</span></p>
        <p class="p4"><span class="s2">10. <span style="text-decoration: underline;">Limitation of Liability</span></span><span class="s1">. CORPORATEGIFT IS NOT LIABLE FOR ANY SPECIAL, INDIRECT, EXEMPLARY, INCIDENTAL, PUNITIVE OR CONSEQUENTIAL DAMAGES OF ANY KIND, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF GOODWILL, WORK STOPPAGE, LOST PROFITS, LOST DATA, FAILURE OR MALFUNCTION, WHETHER OR NOT&nbsp; IT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.&nbsp; CORPORATEGIFT’S LIABILITY HEREUNDER SHALL NOT EXCEED THE TOTAL AMOUNT OF FEES PAID UNDER THIS AGREEMENT FOR THE PRODUCT(S) GIVING RISE TO SUCH LIABILITY. &nbsp;</span></p>
        <p class="p4"><span class="s2">11. <span style="text-decoration: underline;">Suspension or Termination</span>.</span><span class="s1">&nbsp; CorporateGift reserves the right to suspend or terminate Your license to use this Website, without notice, for any reason, at CorporateGift’s discretion.</span></p>
        <p class="p4"><span class="s2">12. <span style="text-decoration: underline;">Forum and Venue</span></span><span class="s1">.&nbsp; By accessing this website, You and CorporateGifts.com agree that the laws and regulations of the State of New Jersey, will apply to all matters relating to Your access of this website, without regard to any conflict of laws principles. In the event of a dispute, You and CorporateGifts.com agree to submit to the exclusive personal jurisdiction and venue of New Jersey with respect to such dispute.</span></p>
        <p class="p4"><span class="s2">13. <span style="text-decoration: underline;">California Users</span>. </span><span class="s1">Under California Civil Code Section 1789.3, California Website users are entitled to the following specific consumer rights notice: The Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs may be contacted in writing at 1625 N. Market Blvd., Suite S-202, Sacramento, California 95834, or by telephone at (800) 952-5210.</span></p>
        <p class="p4"><span class="s2">14. <span style="text-decoration: underline;">Acknowledgment and Changes</span></span><span class="s1">.&nbsp; This Agreement represents the entire understanding between You and the Company regarding Your relationship with the Company and supersedes any prior statements or representations. YOU AGREE TO BE BOUND BY THESE TERMS OF USE by accessing any areas of the Website.&nbsp; CorporateGift reserves the right to change the Terms of Use at any time. If we make any change to the Terms of Use, we will post those changes on this, or any other appropriate page, and they will become effective upon the later of a) the date specified by the Company, if any, or b) the posting. By accessing the Service after changes are made to the Terms of Use and posted on the Service, You agree to be legally bound and to abide by the amended terms.</span></p>
        <p class="p1"><span class="s1">This Agreement is effective as of the date You click “I Agree.” By accessing these terms and clicking “I Agree” You represent and warrant to CorporateGift that You are duly authorized to execute and otherwise enter in this this Agreement on behalf of Customer, and that this Agreement is deemed a binding purchase agreement by Customer.&nbsp;</span></p>
        <p class="p5">&nbsp;</p>
        <p class="p6"><span class="s1">Updated: September 2015.</span></p></div>

</div>

@stop

@push('scripts')

@endpush


